# Generated by Django 2.1.4 on 2019-04-05 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('answer', models.TextField()),
                ('positive_count', models.IntegerField(default=0)),
                ('negative_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('topic', models.CharField(choices=[('sport', 'sport'), ('Law', 'Law'), ('Food', 'Food'), ('Computers', 'Computers'), ('Health', 'Health'), ('Music', 'Music'), ('Science', 'Science'), ('Religion', 'Religion'), ('Tools', 'Tools'), ('time', 'time'), ('Movies', 'Movies'), ('Animals', 'Animals'), ('Clothing', 'Clothing'), ('Holidays', 'Holidays')], default='General', max_length=100)),
                ('word', models.TextField()),
                ('question', models.TextField()),
                ('extensions', models.TextField(default='null')),
                ('difficulty', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1)),
                ('hint', models.TextField(default='null')),
                ('game_mode', models.CharField(choices=[('General', 'General')], default='General', max_length=100)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='app_server', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('user_id', models.TextField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('user_id',),
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_server.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_server.Score'),
        ),
    ]
