# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-31 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('topic', models.CharField(choices=[('General', 'General'), ('Sport', 'Sport')], default='General', max_length=100)),
                ('question', models.TextField()),
                ('extensions', models.TextField()),
                ('difficulty', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1)),
                ('hint', models.TextField()),
                ('game_mode', models.CharField(choices=[('General', 'General')], default='General', max_length=100)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
