# Generated by Django 2.1.4 on 2019-01-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='extensions',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='question',
            name='hint',
            field=models.TextField(default='null'),
        ),
    ]
