# Generated by Django 2.1.4 on 2019-05-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.CharField(choices=[('SAT vocabulary', 'SAT vocabulary'), ('GRE vocabulary', 'GRE vocabulary'), ('sport', 'sport'), ('Law', 'Law'), ('Food', 'Food'), ('Computers', 'Computers'), ('Music', 'Music'), ('Science', 'Science'), ('Religion', 'Religion'), ('Tools', 'Tools'), ('Movies', 'Movies'), ('Animals', 'Animals'), ('Clothing', 'Clothing'), ('Holidays', 'Holidays')], default='General', max_length=100),
        ),
    ]
