# Generated by Django 2.1.4 on 2019-06-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_server', '0002_auto_20190515_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='user_name',
            field=models.TextField(default='no_name'),
        ),
    ]
