# Generated by Django 2.1.4 on 2019-01-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_server', '0004_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
